### ISSUE TITLE
Why use Selenium when you can use Discord API?

### ISSUE THREAD

**Issue by MehulKhanna** [qqqwda/pokemeow-autoplay#5]

**Comment by qqqwda** [comment]
hey @MehulKhanna ! I'm using Selenium because it actually opens a browser for you, you can still pause the Autoplay bot and do whatever you want (like check inventory, buy your own balls or check the ;research command)

btw I really like your pokegrinder https://github.com/MehulKhanna/PokeGrinder
nice work :)
